# Configurations
title:            Utopian Orbit
longtitle:        Utopian Orbit
author:           Jihanger
email:            utopian.orbit@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Psychedelic poetry and game design. A trip of the unseen,
  for the Children With No Name.

version:          1.0
gitbook_version:  3.2.3

url:              ''
baseurl:          '/utopian_orbit_blog/'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
